# Generated by Django 2.2.4 on 2022-09-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Show',
        ),
    ]
